/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * form_utama.java
 *
 * 
 */

package sipegadaian;

import Editing.EditBarang;
import Editing.Edit_Employee;
import Editing.Edit_Nasabah;
import Editing.Edit_trans_keluar;
import Editing.Edit_trans_masuk;
import Entry.EntryAdmin;
import Entry.EntryNasabah;
import Entry.EntryEmployee;
import Entry.EntryBarang;
import java.awt.Dimension;
import java.awt.Toolkit;
import transaksi.trans_keluar;
import transaksi.trans_masuk;

/**
 *
 * @author Danny1
 */
public class form_utama extends javax.swing.JFrame {
public Dimension ukuran_layar;

    /** Creates new form form_utama */
    public form_utama() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        logOff = new javax.swing.JMenuItem();
        Close = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        masuk = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Entrybarang = new javax.swing.JMenuItem();
        EntryEmployee = new javax.swing.JMenuItem();
        EntryNasabah = new javax.swing.JMenuItem();
        EntryAdministrator = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        data_barang = new javax.swing.JMenuItem();
        data_employee = new javax.swing.JMenuItem();
        data_customer = new javax.swing.JMenuItem();
        data_trans_masuk = new javax.swing.JMenuItem();
        data_trans_keluar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM INFORMASI PEGADAIAN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(203, 238, 13));
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 650);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));

        file.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BRANCH.PNG"))); // NOI18N
        file.setMnemonic('F');
        file.setText("File");

        logOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logoff.png"))); // NOI18N
        logOff.setText("Log Off");
        logOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOffActionPerformed(evt);
            }
        });
        file.add(logOff);

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        Close.setText("Exit");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        file.add(Close);

        jMenuBar1.add(file);

        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SalesRep.png"))); // NOI18N
        transaksi.setMnemonic('T');
        transaksi.setText("Transaksi");

        masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1303561639_Buy.png"))); // NOI18N
        masuk.setText("transaksi masuk");
        masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukActionPerformed(evt);
            }
        });
        transaksi.add(masuk);

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1303777383_Dollar Sign.png"))); // NOI18N
        keluar.setText("transaksi keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        transaksi.add(keluar);

        jMenuBar1.add(transaksi);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SAVE.PNG"))); // NOI18N
        jMenu2.setMnemonic('I');
        jMenu2.setText("Input/ Update Data");

        Entrybarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bModify.png"))); // NOI18N
        Entrybarang.setText("Entry Barang");
        Entrybarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrybarangActionPerformed(evt);
            }
        });
        jMenu2.add(Entrybarang);

        EntryEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bModify.png"))); // NOI18N
        EntryEmployee.setText("Entry Employee");
        EntryEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryEmployeeActionPerformed(evt);
            }
        });
        jMenu2.add(EntryEmployee);

        EntryNasabah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bModify.png"))); // NOI18N
        EntryNasabah.setText("Entry Nasabah");
        EntryNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryNasabahActionPerformed(evt);
            }
        });
        jMenu2.add(EntryNasabah);

        EntryAdministrator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bModify.png"))); // NOI18N
        EntryAdministrator.setText("Entry Administrator");
        EntryAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryAdministratorActionPerformed(evt);
            }
        });
        jMenu2.add(EntryAdministrator);

        jMenuBar1.add(jMenu2);

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bModify.png"))); // NOI18N
        edit.setMnemonic('E');
        edit.setText("Edit");

        data_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        data_barang.setText("Data Barang");
        data_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_barangActionPerformed(evt);
            }
        });
        edit.add(data_barang);

        data_employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        data_employee.setText("Data Employee");
        data_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_employeeActionPerformed(evt);
            }
        });
        edit.add(data_employee);

        data_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        data_customer.setText("Data Nasabah");
        data_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_customerActionPerformed(evt);
            }
        });
        edit.add(data_customer);

        data_trans_masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        data_trans_masuk.setText("Data Transaksi Masuk");
        data_trans_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_trans_masukActionPerformed(evt);
            }
        });
        edit.add(data_trans_masuk);

        data_trans_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        data_trans_keluar.setText("Data Transaksi Keluar");
        data_trans_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_trans_keluarActionPerformed(evt);
            }
        });
        edit.add(data_trans_keluar);

        jMenuBar1.add(edit);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PRINT.PNG"))); // NOI18N
        jMenu3.setMnemonic('L');
        jMenu3.setText("Laporan");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1303562470_agt_print.png"))); // NOI18N
        jMenuItem2.setText("Detail Barang");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:        
        ukuran_layar=Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((ukuran_layar.width / 2) - (getSize().width / 2), (ukuran_layar.height / 2) - (getSize().height / 2));
    }//GEN-LAST:event_formWindowActivated

    private void masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukActionPerformed
        // TODO add your handling code here:
trans_masuk form_masuk=new trans_masuk();
jDesktopPane1.add(form_masuk,javax.swing.JLayeredPane.DEFAULT_LAYER);
form_masuk.show();
    }//GEN-LAST:event_masukActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
trans_keluar form_keluar=new trans_keluar();
jDesktopPane1.add(form_keluar,javax.swing.JLayeredPane.DEFAULT_LAYER);
form_keluar.show();
    }//GEN-LAST:event_keluarActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_CloseActionPerformed

    private void data_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_employeeActionPerformed
        // TODO add your handling code here:
Edit_Employee form_Employee=new Edit_Employee();
jDesktopPane1.add(form_Employee,javax.swing.JLayeredPane.DEFAULT_LAYER);
form_Employee.show();
    }//GEN-LAST:event_data_employeeActionPerformed

    private void data_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_barangActionPerformed
        // TODO add your handling code here:
EditBarang form_Barang=new EditBarang();
jDesktopPane1.add(form_Barang,javax.swing.JLayeredPane.DEFAULT_LAYER);
form_Barang.show();
    }//GEN-LAST:event_data_barangActionPerformed

    private void data_trans_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_trans_keluarActionPerformed
        // TODO add your handling code here:
Edit_trans_keluar cekout=new Edit_trans_keluar();
jDesktopPane1.add(cekout,javax.swing.JLayeredPane.DEFAULT_LAYER);
cekout.show();
    }//GEN-LAST:event_data_trans_keluarActionPerformed

    private void EntrybarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrybarangActionPerformed
        // TODO add your handling code here:
EntryBarang barangmasuk=new EntryBarang();
jDesktopPane1.add(barangmasuk,javax.swing.JLayeredPane.DEFAULT_LAYER);
barangmasuk.show();
    }//GEN-LAST:event_EntrybarangActionPerformed

    private void EntryEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryEmployeeActionPerformed
        // TODO add your handling code here:
EntryEmployee employeecall=new EntryEmployee();
jDesktopPane1.add(employeecall,javax.swing.JLayeredPane.DEFAULT_LAYER);
employeecall.show();
    }//GEN-LAST:event_EntryEmployeeActionPerformed

    private void EntryNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryNasabahActionPerformed
        // TODO add your handling code here:
EntryNasabah penabungku=new EntryNasabah();
jDesktopPane1.add(penabungku,javax.swing.JLayeredPane.DEFAULT_LAYER);
penabungku.show();
    }//GEN-LAST:event_EntryNasabahActionPerformed

    private void logOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOffActionPerformed
        // TODO add your handling code here:
form_login x=new form_login();
this.dispose();
x.setVisible(true);
    }//GEN-LAST:event_logOffActionPerformed

    private void data_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_customerActionPerformed
        // TODO add your handling code here:
Edit_Nasabah nasabah=new Edit_Nasabah();
jDesktopPane1.add(nasabah,javax.swing.JLayeredPane.DEFAULT_LAYER);
nasabah.show();
    }//GEN-LAST:event_data_customerActionPerformed

    private void data_trans_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_trans_masukActionPerformed
        // TODO add your handling code here:
Edit_trans_masuk cekin=new Edit_trans_masuk();
jDesktopPane1.add(cekin,javax.swing.JLayeredPane.DEFAULT_LAYER);
cekin.show();
    }//GEN-LAST:event_data_trans_masukActionPerformed

    private void EntryAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryAdministratorActionPerformed
        // TODO add your handling code here:
EntryAdmin x=new EntryAdmin();
jDesktopPane1.add(x,javax.swing.JLayeredPane.DEFAULT_LAYER);
x.show();
    }//GEN-LAST:event_EntryAdministratorActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Close;
    private javax.swing.JMenuItem EntryAdministrator;
    private javax.swing.JMenuItem EntryEmployee;
    private javax.swing.JMenuItem EntryNasabah;
    private javax.swing.JMenuItem Entrybarang;
    private javax.swing.JMenuItem data_barang;
    private javax.swing.JMenuItem data_customer;
    private javax.swing.JMenuItem data_employee;
    private javax.swing.JMenuItem data_trans_keluar;
    private javax.swing.JMenuItem data_trans_masuk;
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JMenuItem logOff;
    private javax.swing.JMenuItem masuk;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables

}
