/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * form_login.java
 *
 * Created on Apr 1, 2011, 12:30:24 AM
 */

package sipegadaian;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Danny1
 */
public class form_login extends javax.swing.JFrame {

    /** Creates new form form_login */
    public form_login() {
        initComponents();
    }
public Dimension ukuran_layar;
public Connection konek=null;
public Statement st=null;
public ResultSet rs=null;
public koneksi conn=new koneksi();
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
public boolean peryataan=false;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnia = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btclose = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEM INFORMASI PEGADAIAN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel1.setForeground(new java.awt.Color(249, 239, 239));
        jLabel1.setText("NIA :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 40, 20));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel2.setForeground(new java.awt.Color(249, 239, 239));
        jLabel2.setText("PASSWORD :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 100, 20));
        getContentPane().add(txtnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, 20));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 170, 20));

        btclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        btclose.setText("CLOSE");
        btclose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));

        btreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1303726327_Reset.png"))); // NOI18N
        btreset.setText("RESET");
        btreset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });
        getContentPane().add(btreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 90, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kgpg_identity.png"))); // NOI18N
        jButton3.setText("LOGIN");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Login form .png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public boolean  getData(){
    Object [][] data=null;

    String nia=txtnia.getText();
    String pwd=new String(txtpass.getPassword());

    String getNia =null;
    String getPass = null;

    try{
        Class.forName("com.mysql.jdbc.Driver");        
        konek=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sipegadaian","root","");        
        st= (Statement) konek.createStatement();        
        String query="SELECT * FROM login;";
        rs=st.executeQuery(query);        
        rs.last();
        int baris=rs.getRow();
        rs.beforeFirst();
        data=new Object[baris][2];
        int no=-1;
        while(rs.next()){
            no++;
            data[no][0]=rs.getString("nia");
            getNia=data[no][0].toString();
            data[no][1]=rs.getString("password");
            getPass=data[no][1].toString();
        }
        rs.close();
        st.close();
    }
    catch(Exception e){
        
    }
/*    JOptionPane.showMessageDialog(rootPane, "nia = "+nia);
    JOptionPane.showMessageDialog(rootPane, "pass = "+pwd);
    JOptionPane.showMessageDialog(rootPane, "getnia = "+getNia);
    JOptionPane.showMessageDialog(rootPane, "getpass= "+getPass);*/

    if(nia.equals(getNia) && getNia.equals(getPass)){
        peryataan=true;
        JOptionPane.showMessageDialog(null, "Selamat Login Berhasil","Sistem Informasi Pegadaian",JOptionPane.INFORMATION_MESSAGE);
    }
    else{
        peryataan=false;
     JOptionPane.showMessageDialog(rootPane, "Login Gagal");
    }    
    return peryataan;
}
    private void btcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btcloseActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
ukuran_layar=Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((ukuran_layar.width / 2) - (getSize().width / 2), (ukuran_layar.height / 2) - (getSize().height / 2));
    }//GEN-LAST:event_formWindowActivated

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
            txtnia.requestFocus();
            txtnia.setText("");
            txtpass.setText("");
    }//GEN-LAST:event_btresetActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
boolean fix=getData();
        if(fix==true){
            this.dispose();
            new form_utama().setVisible(true);
        }
        else{
            txtnia.requestFocus();
            txtnia.setText("");
            txtpass.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btclose;
    private javax.swing.JButton btreset;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtnia;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables

}
