/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntryEmployee.java
 *
 * Created on Apr 22, 2016, 4:11:06 PM
 */

package Editing;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sipegadaian.koneksi;

/**
 *
 * @author Danny1
 */
public class Edit_Employee extends javax.swing.JInternalFrame {
    /** Creates new form EntryEmployee */
    public Edit_Employee() {
        initComponents();
        showTable(getData());
    }
public koneksi konek=new koneksi();
public Connection conn=null;
public ResultSet rs=null;
public Statement st=null;
public JTable tbEmployee;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtidemployee = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btclose = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btcari = new javax.swing.JButton();
        BTUPDATE = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btcekID = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Edit Employee");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("IDEMPLOYEE :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));
        getContentPane().add(txtidemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 50, 20));

        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
        });
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, 20));

        txtalamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtalamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtalamatFocusLost(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 140, 20));

        jLabel3.setText("ALAMAT :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, 20));

        jLabel2.setText("NAMA  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        btclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1303725710_button_cancel.png"))); // NOI18N
        btclose.setText("CLOSE");
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 120, 30));
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 70, -1));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 13, 13));
        jLabel10.setText("Cari Berdasarkan Nama :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        btcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SEARCH.PNG"))); // NOI18N
        btcari.setText("CARI");
        btcari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        getContentPane().add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 60, 20));

        BTUPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bModify.png"))); // NOI18N
        BTUPDATE.setText("UPDATE");
        BTUPDATE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTUPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(BTUPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, 30));

        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.jpg"))); // NOI18N
        btdelete.setText("DELETE");
        btdelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 120, 30));

        btcekID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ok.png"))); // NOI18N
        btcekID.setText("CEK");
        btcekID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcekIDActionPerformed(evt);
            }
        });
        getContentPane().add(btcekID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, 20));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 370, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PEGAWAI.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int len(String field){
    int len=field.length();
    return len;
}
    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        // TODO add your handling code here:
        if(len(txtidemployee.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "ID Employee tidak boleh kosong");
            txtidemployee.requestFocus();
            txtidemployee.setText("12345");
        }
        if(len(txtidemployee.getText())<5 || len(txtidemployee.getText())>5){
            JOptionPane.showMessageDialog(rootPane, "ID Employee Kurang lengkap");
            txtidemployee.setText("12345");
            txtidemployee.requestFocus();
        }
}//GEN-LAST:event_txtnamaFocusGained

    private void txtalamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalamatFocusGained
        // TODO add your handling code here:
        if(len(txtnama.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Nama employee harus diisi");
            txtnama.setText("employee");
            txtnama.requestFocus();
        }
}//GEN-LAST:event_txtalamatFocusGained

    private void txtalamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalamatFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatFocusLost
public String getID(){
    String id=txtidemployee.getText();
    return id;
}
public String getAlamat(){
    String alamat=txtalamat.getText();
    return alamat;
}
public String getNama(){
    String nama=txtnama.getText();
    return nama;
}
    private void btcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btcloseActionPerformed

    private void BTUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTUPDATEActionPerformed
        // TODO add your handling code here:
try{
        konek.konek();
        PreparedStatement ps=null;
        String query="update employee set nama=?, alamat=? where idemployee=?";
        ps= (PreparedStatement) conn.prepareStatement(query);
        ps.setString(1, txtnama.getText());
        ps.setString(2, txtalamat.getText());
        ps.setString(3, txtidemployee.getText());

        int ok=ps.executeUpdate();
        if(ok>0){
            JOptionPane.showMessageDialog(this, "Edit data Employee sukses","Informasi",JOptionPane.INFORMATION_MESSAGE);
            showTable(getData());
        }
        else{
            JOptionPane.showMessageDialog(this, "Edit data Employee gagal","Informasi",JOptionPane.INFORMATION_MESSAGE);
            showTable(getData());
        }
        ps.close();
        isClear();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Editing data gagal karena "+e);
    }
    }//GEN-LAST:event_BTUPDATEActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
showTable(getDataCari());
    }//GEN-LAST:event_btcariActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        int konfirmasi=JOptionPane.showConfirmDialog(rootPane, "apakah anda yakin ingin menghapus ? ", "haspus",JOptionPane.YES_NO_CANCEL_OPTION);
        if(konfirmasi==JOptionPane.YES_OPTION){
            String idbarang=tbEmployee.getValueAt(tbEmployee.getSelectedRow(),0).toString();
            try{
                konek.konek();
                PreparedStatement ps=null;
                String query="DELETE FROM employee WHERE idemployee=?";
                ps=(PreparedStatement) conn.prepareStatement(query);
                ps.setString(1, idbarang);
                int ok=ps.executeUpdate();
                if(ok==1)
                    JOptionPane.showMessageDialog(this,"DELETE berhasil","DELETE",JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this,"DELETE GAGAL","DELETE",JOptionPane.INFORMATION_MESSAGE);
                ps.close();
                showTable(getData());
            } catch(SQLException e){
                System.out.println("HAPUS data GAGAL karena"+e.toString());
            }
        } else{
            System.out.print("penghapusan digagalkan");
        }
}//GEN-LAST:event_btdeleteActionPerformed

    private void btcekIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcekIDActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
                        //JOptionPane.showMessageDialog(null, "DRIVER OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
                        //JOptionPane.showMessageDialog(null, "KONEKSI OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            st=(Statement) conn.createStatement();
                        //JOptionPane.showMessageDialog(null, "CREATE STATEMENT OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            rs=st.executeQuery("SELECT * FROM employee WHERE '"+txtidemployee.getText()+"';");            
                        //JOptionPane.showMessageDialog(null, "SELECT Employee OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "ID Barang : Benar","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
                BTUPDATE.setEnabled(true);                
                txtnama.setText(rs.getString("nama"));
                txtalamat.setText(rs.getString("alamat"));                
            } else{
                JOptionPane.showMessageDialog(null, "ID Barang : Salah","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
                BTUPDATE.setEnabled(false);
                isClear();
                txtidemployee.requestFocus();
            }
        } catch(Exception e){

        }
}//GEN-LAST:event_btcekIDActionPerformed
void isClear(){
    txtalamat.setText("");
    txtcari.setText("");
    txtidemployee.setText("");
    txtnama.setText("");
}
    public Object [][] getData(){
    Object [][]data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st=(Statement) conn.createStatement();
        String query="SELECT * FROM employee;";
        rs=st.executeQuery(query);
        rs.last();
        int baris=rs.getRow();
        rs.beforeFirst();
        data=new Object[baris][3];
        int no=-1;
        while(rs.next()){
            no++;
            data[no][0]=rs.getString("idemployee");
            data[no][1]=rs.getString("nama");
            data[no][2]=rs.getString("alamat");
        }
        st.close();
    }
    catch(Exception e){

    }
    return data;
}
    public Object [][] getDataCari(){
    Object [][]data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st=(Statement) conn.createStatement();
        String query="SELECT * FROM employee WHERE nama LIKE ('%"+txtcari.getText()+"%');";
        rs=st.executeQuery(query);
        rs.last();
        int baris=rs.getRow();
        rs.beforeFirst();
        data=new Object[baris][3];
        int no=-1;
        while(rs.next()){
            no++;
            data[no][0]=rs.getString("idemployee");
            data[no][1]=rs.getString("nama");
            data[no][2]=rs.getString("alamat");
        }
        st.close();
    }
    catch(Exception e){

    }
    return data;
}
public void showTable(Object [][] data){
    String []nama_kolom={"idemployee","nama","alamat"};
    tbEmployee =new JTable(data, nama_kolom);
    jScrollPane1.setViewportView(tbEmployee);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTUPDATE;
    private javax.swing.JButton btcari;
    private javax.swing.JButton btcekID;
    private javax.swing.JButton btclose;
    private javax.swing.JButton btdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtidemployee;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

}
