/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * trans_masuk.java
 *
 * Created on Apr 23, 2016, 6:17:38 AM
 */

package Editing;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sipegadaian.koneksi;
import java.text.SimpleDateFormat;
/**
 *
 * @author Danny1
 */
public class Edit_trans_keluar extends javax.swing.JInternalFrame {

    /** Creates new form trans_masuk */
    public Edit_trans_keluar() {
        initComponents();
        showTable(getData());
    }
public Connection conn=null;
public Statement st=null;
public ResultSet rs=null;
public koneksi konek=new koneksi();
public JTable tblTran_keluar=null;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btcari = new javax.swing.JButton();
        txtnoresi = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        BTUPDATE = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        txttgl = new com.toedter.calendar.JDateChooser();
        btcekID = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Transaksi Keluar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NO. RESI :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        btcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SEARCH.PNG"))); // NOI18N
        btcari.setText("CARI");
        btcari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        getContentPane().add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 60, -1));
        getContentPane().add(txtnoresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 50, -1));
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 50, -1));

        jLabel2.setText("JUMLAH BARANG:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel3.setText("TOTAL :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 105, -1));

        jLabel4.setText("TGL TRANSAKSI :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        btclose.setText("CLOSE");
        btclose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 400, 210));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        jLabel10.setForeground(new java.awt.Color(25, 13, 13));
        jLabel10.setText("Cari Berdasarkan nomor resi :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 80, -1));

        BTUPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bModify.png"))); // NOI18N
        BTUPDATE.setText("UPDATE");
        BTUPDATE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTUPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(BTUPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 30));

        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.jpg"))); // NOI18N
        btdelete.setText("DELETE");
        btdelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, 30));
        getContentPane().add(txttgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 110, -1));

        btcekID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ok.png"))); // NOI18N
        btcekID.setText("CEK");
        btcekID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcekIDActionPerformed(evt);
            }
        });
        getContentPane().add(btcekID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TRANSAKSI KELUAR.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String getNoresi(){
    String noresi=txtnoresi.getText();
    return noresi;
}
public String getJumlah(){
    String jumlah=txtjumlah.getText();
    return jumlah;
}
public String getTotal(){
    String total=txttotal.getText();
    return total;
}
public String getTgl(){
    String tgl = null;
    if(txttgl.getDate()!=null){
        SimpleDateFormat ganti=new SimpleDateFormat("yyyy-MM-dd");
        tgl=ganti.format(txttgl.getDate());
    }
    return tgl;
}
private Object [][] getData(){
    Object [][] data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st= (Statement) conn.createStatement();
        String query="SELECT * FROM tran_keluar;";
        rs=st.executeQuery(query);
        rs.last();
        int row=rs.getRow();
        rs.beforeFirst();        
        data=new Object[row][4];
        int index=-1;
        while(rs.next()){
            index++;
            data[index][0]=rs.getString("no_resi");
            data[index][1]=rs.getString("jumlah");
            data[index][2]=rs.getString("total");
            data[index][3]=rs.getString("tgl_transaksi");
        }
        st.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, "ERROR karena "+e);
    }
    return data;
}
private Object [][] getDataCari(){
    Object [][] data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st= (Statement) conn.createStatement();
        String query="SELECT * FROM tran_keluar WHERE no_resi LIKE ('"+txtcari.getText()+"');";
        rs=st.executeQuery(query);
        rs.last();
        int row=rs.getRow();
        rs.beforeFirst();
        data=new Object[row][4];
        int index=-1;
        while(rs.next()){
            index++;
            data[index][0]=rs.getString("no_resi");
            data[index][1]=rs.getString("jumlah");
            data[index][2]=rs.getString("total");
            data[index][3]=rs.getString("tgl_transaksi");
        }
        st.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, "ERROR karena "+e);
    }
    return data;
}
public void showTable(Object [][] data){
    String [] col_names={"no_resi","jumlah","total","tgl_transaksi"};
    tblTran_keluar=new JTable(data, col_names);
    jScrollPane1.setViewportView(tblTran_keluar);
}
    private void btcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btcloseActionPerformed

    private void BTUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTUPDATEActionPerformed
        // TODO add your handling code here:
try{
        konek.konek();
        PreparedStatement ps=null;
        String query="update tran_keluar set jumlah=?, total=? , tgl_transaksi=? where no_resi=?";
        ps= (PreparedStatement) conn.prepareStatement(query);
        ps.setString(1, txtjumlah.getText());
        ps.setString(2, txttotal.getText());
        ps.setString(3, getTgl());
        ps.setString(4, txtnoresi.getText());

        int ok=ps.executeUpdate();
        if(ok>0){
            JOptionPane.showMessageDialog(this, "Edit data Transaksi Keluar sukses","Informasi",JOptionPane.INFORMATION_MESSAGE);
            showTable(getData());
        }
        else{
            JOptionPane.showMessageDialog(this, "Edit data Transaksi Keluar gagal","Informasi",JOptionPane.INFORMATION_MESSAGE);
            showTable(getData());
        }
        ps.close();
        isClear();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Editing data gagal karena "+e);
    }
}//GEN-LAST:event_BTUPDATEActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        int konfirmasi=JOptionPane.showConfirmDialog(rootPane, "apakah anda yakin ingin menghapus ? ", "haspus",JOptionPane.YES_NO_CANCEL_OPTION);
        if(konfirmasi==JOptionPane.YES_OPTION){
            String idbarang=tblTran_keluar.getValueAt(tblTran_keluar.getSelectedRow(),0).toString();
            try{
                konek.konek();
                PreparedStatement ps=null;
                String query="DELETE FROM tran_keluar WHERE no_resi=?";
                ps=(PreparedStatement) conn.prepareStatement(query);
                ps.setString(1, idbarang);
                int ok=ps.executeUpdate();
                if(ok==1)
                    JOptionPane.showMessageDialog(this,"DELETE berhasil","DELETE",JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this,"DELETE GAGAL","DELETE",JOptionPane.INFORMATION_MESSAGE);
                ps.close();
                showTable(getData());
            } catch(SQLException e){
                System.out.println("HAPUS data GAGAL karena"+e.toString());
            }
        } else{
            System.out.print("penghapusan digagalkan");
        }
}//GEN-LAST:event_btdeleteActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
showTable(getDataCari());
txtcari.requestFocus();
    }//GEN-LAST:event_btcariActionPerformed

    private void btcekIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcekIDActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //JOptionPane.showMessageDialog(null, "DRIVER OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
            //JOptionPane.showMessageDialog(null, "KONEKSI OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            st=(Statement) conn.createStatement();
            //JOptionPane.showMessageDialog(null, "CREATE STATEMENT OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            rs=st.executeQuery("SELECT * FROM tran_keluar WHERE '"+txtnoresi.getText()+"';");
            //+ "WHERE idbarang='"+txtIDbarang.getText()+"'"
            //JOptionPane.showMessageDialog(null, "SELECT RESI OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "NO RESI : Benar","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
                BTUPDATE.setEnabled(true);
                txtjumlah.setText(rs.getString("jumlah"));
                txttotal.setText(rs.getString("total"));
            } else{
                JOptionPane.showMessageDialog(null, "NO RESI : Salah","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
                BTUPDATE.setEnabled(false);
                isClear();
                txtnoresi.requestFocus();
            }
        } catch(Exception e){

        }
}//GEN-LAST:event_btcekIDActionPerformed
void isClear(){
    txtcari.setText("");
    txtjumlah.setText("");
    txtnoresi.setText("");
    txttgl.setCalendar(null);
    txttotal.setText("");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTUPDATE;
    private javax.swing.JButton btcari;
    private javax.swing.JButton btcekID;
    private javax.swing.JButton btclose;
    private javax.swing.JButton btdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnoresi;
    private com.toedter.calendar.JDateChooser txttgl;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

}
