/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntryNasabah.java
 *
 * Created on Apr 22, 2016, 6:26:41 PM
 */

package Editing;

import Entry.*;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sipegadaian.koneksi;

/**
 *
 * @author Danny1
 */
public class Edit_Nasabah extends javax.swing.JInternalFrame {
public koneksi konek=new koneksi();
public Connection conn=null;
public Statement st=null;
public ResultSet rs=null;
public JTable tabel;
    /** Creates new form EntryNasabah */
    public Edit_Nasabah() {
        initComponents();
        showTable(getData());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtidnasabah = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttelp = new javax.swing.JTextField();
        btclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btcari = new javax.swing.JButton();
        BTUPDATE = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btcekID = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID NASABAH :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));
        getContentPane().add(txtidnasabah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 70, 20));

        txtalamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtalamatFocusGained(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 160, 20));

        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
        });
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 20));

        jLabel2.setText("NAMA :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel3.setText("ALAMAT :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        jLabel4.setText("KTP / SIM :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 20));

        txttelp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelpFocusGained(evt);
            }
        });
        getContentPane().add(txttelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 160, 20));

        btclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        btclose.setText("CLOSE");
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 360, 120));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 13, 13));
        jLabel10.setText("Cari Berdasarkan Nama :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 90, -1));

        btcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SEARCH.PNG"))); // NOI18N
        btcari.setText("CARI");
        btcari.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        getContentPane().add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 60, 20));

        BTUPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bModify.png"))); // NOI18N
        BTUPDATE.setText("UPDATE");
        BTUPDATE.setBorder(new javax.swing.border.SoftBevelBorder(0));
        BTUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTUPDATEActionPerformed(evt);
            }
        });
        getContentPane().add(BTUPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 110, 30));

        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.jpg"))); // NOI18N
        btdelete.setText("DELETE");
        btdelete.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 100, 30));

        btcekID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ok.png"))); // NOI18N
        btcekID.setText("CEK");
        btcekID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcekIDActionPerformed(evt);
            }
        });
        getContentPane().add(btcekID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, 20));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setText("NO TELP :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int len(String field){
    int len=field.length();
    return len;
}
   public String getID(){
        String id=txtidnasabah.getText();
        return id;
    }
    public String getNama(){
        String nama=txtnama.getText();
        return nama;
    }
    public String getAlamat(){
        String alamat=txtalamat.getText();
        return alamat;
    }
    public String getTelp(){
        String telp=txttelp.getText();
        return telp;
    }
    private void txtalamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalamatFocusGained
        // TODO add your handling code here:
        if(len(txtnama.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Tidak boleh kosong");
            txtnama.setText("NAME");
            txtnama.requestFocus();
        }
}//GEN-LAST:event_txtalamatFocusGained

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        // TODO add your handling code here:
        if(len(txtidnasabah.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Tidak boleh kosong");
            txtidnasabah.setText("12345");
            txtidnasabah.requestFocus();
        }
        if(len(txtidnasabah.getText())<5 && len(txtidnasabah.getText())>5){
            JOptionPane.showMessageDialog(rootPane, "harus 5 digit");
            txtidnasabah.setText("12345");
            txtidnasabah.requestFocus();
        }
}//GEN-LAST:event_txtnamaFocusGained

    private void txttelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelpFocusGained
        // TODO add your handling code here:
        if(len(txtalamat.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Tidak boleh kosong");
            txtalamat.setText("ADDRESS");
            txtalamat.requestFocus();
        }
}//GEN-LAST:event_txttelpFocusGained

    public Object [][] getData(){
    Object [][] data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st= (Statement) conn.createStatement();
        String Query="Select * from nasabah;";
        rs=st.executeQuery(Query);
        rs.last();
        int baris=rs.getRow();
        rs.beforeFirst();        
        data=new Object[baris][4];
        int no=-1;
        while(rs.next()){
            no++;
            data[no][0]=rs.getString("idnasabah");
            data[no][1]=rs.getString("nama");
            data[no][2]=rs.getString("alamat");
            data[no][3]=rs.getString("no_telp");
        }
        st.close();
    }
    catch(Exception e){
        System.out.print("Error Karena = "+e);
    }
    return data;
}
public Object [][] getDataCari(){
    Object [][] data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st= (Statement) conn.createStatement();
        String Query="Select * from nasabah WHERE nama LIKE ('%"+txtcari.getText()+"%');";
        rs=st.executeQuery(Query);
        rs.last();
        int baris=rs.getRow();
        rs.beforeFirst();
        data=new Object[baris][4];
        int no=-1;
        while(rs.next()){
            no++;
            data[no][0]=rs.getString("idnasabah");
            data[no][1]=rs.getString("nama");
            data[no][2]=rs.getString("alamat");
            data[no][3]=rs.getString("no_telp");
        }
        st.close();
    }
    catch(Exception e){
        System.out.print("Error Karena = "+e);
    }
    return data;
}
public void showTable(Object[][] data){
    String [] nama_kol={"IdNasabah","Nama","Alamat","No_Telp"};
    tabel =new JTable(data,nama_kol);
    jScrollPane1.setViewportView(tabel);
}
    private void btcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btcloseActionPerformed

    private void BTUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTUPDATEActionPerformed
        // TODO add your handling code here:
try{
        konek.konek();
        PreparedStatement ps=null;
        String query="update nasabah set nama=?, alamat=? , no_telp=? where idnasabah=?";
        ps= (PreparedStatement) conn.prepareStatement(query);
        ps.setString(1, txtnama.getText());
        ps.setString(2, txtalamat.getText());
        ps.setString(3, txttelp.getText());
        ps.setString(4, txtidnasabah.getText());

        int ok=ps.executeUpdate();
        if(ok>0){
            JOptionPane.showMessageDialog(this, "Edit data Nasabah sukses","Informasi",JOptionPane.INFORMATION_MESSAGE);
            showTable(getData());
        }
        else{
            JOptionPane.showMessageDialog(this, "Edit data Nasabah gagal","Informasi",JOptionPane.INFORMATION_MESSAGE);
            showTable(getData());
        }
        ps.close();
        isClear();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Editing data gagal karena "+e);
    }
}//GEN-LAST:event_BTUPDATEActionPerformed
void isClear(){
    txtalamat.setText("");
    txtcari.setText("");
    txtidnasabah.setText("");
    txtnama.setText("");
    txttelp.setText("");
}
    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        int konfirmasi=JOptionPane.showConfirmDialog(rootPane, "apakah anda yakin ingin menghapus ? ", "haspus",JOptionPane.YES_NO_CANCEL_OPTION);
        if(konfirmasi==JOptionPane.YES_OPTION){
            String idbarang=tabel.getValueAt(tabel.getSelectedRow(),0).toString();
            try{
                konek.konek();
                PreparedStatement ps=null;
                String query="DELETE FROM nasabah WHERE idnasabah=?";
                ps=(PreparedStatement) conn.prepareStatement(query);
                ps.setString(1, idbarang);
                int ok=ps.executeUpdate();
                if(ok==1)
                    JOptionPane.showMessageDialog(this,"DELETE berhasil","DELETE",JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this,"DELETE GAGAL","DELETE",JOptionPane.INFORMATION_MESSAGE);
                ps.close();
                showTable(getData());
            } catch(SQLException e){
                System.out.println("HAPUS data GAGAL karena"+e.toString());
            }
        } else{
            System.out.print("penghapusan digagalkan");
        }
}//GEN-LAST:event_btdeleteActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
showTable(getDataCari());
txtcari.requestFocus();
    }//GEN-LAST:event_btcariActionPerformed

    private void btcekIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcekIDActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            //JOptionPane.showMessageDialog(null, "DRIVER OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
            //JOptionPane.showMessageDialog(null, "KONEKSI OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            st=(Statement) conn.createStatement();
            //JOptionPane.showMessageDialog(null, "CREATE STATEMENT OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            rs=st.executeQuery("SELECT * FROM nasabah WHERE '"+txtidnasabah.getText()+"';");
            //+ "WHERE idbarang='"+txtIDbarang.getText()+"'"
            //JOptionPane.showMessageDialog(null, "SELECT Nasabah OK","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "ID Nasabah : Benar","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
                BTUPDATE.setEnabled(true);
                txtnama.setText(rs.getString("nama"));
                txtalamat.setText(rs.getString("alamat"));
                txttelp.setText(rs.getString("no_telp"));
            } else{
                JOptionPane.showMessageDialog(null, "ID Nasabah : Salah","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
                BTUPDATE.setEnabled(false);
                isClear();
                txtidnasabah.requestFocus();
            }
        } catch(Exception e){

        }
}//GEN-LAST:event_btcekIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTUPDATE;
    private javax.swing.JButton btcari;
    private javax.swing.JButton btcekID;
    private javax.swing.JButton btclose;
    private javax.swing.JButton btdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtidnasabah;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelp;
    // End of variables declaration//GEN-END:variables

}
