/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * trans_keluar.java
 *
 * 
 */

package transaksi;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sipegadaian.koneksi;
import java.text.SimpleDateFormat;

/**
 *
 * @author Danny1
 */
public class trans_keluar extends javax.swing.JInternalFrame {

    /** Creates new form trans_keluar */
    public trans_keluar() {
        initComponents();
        showTable();
    }
public Connection conn=null;
public Statement st=null;
public ResultSet rs=null;
public koneksi konek=new koneksi();
public JTable tblTran_keluar=null;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnoresi = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btsave = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btdelete1 = new javax.swing.JButton();
        btnew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txttgl = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnoresi1 = new javax.swing.JTextField();
        btcari = new javax.swing.JButton();

        setTitle("Transakasi Keluar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID NASABAH :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, -1));
        getContentPane().add(txtnoresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, -1));
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 50, -1));

        jLabel2.setText("JUMLAH BARANG:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel3.setText("TOTAL :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 100, -1));

        jLabel4.setText("TGL TRANSAKSI :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        btsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SAVE.PNG"))); // NOI18N
        btsave.setText("SAVE");
        btsave.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 80, 30));

        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/CANCEL.PNG"))); // NOI18N
        btdelete.setText("DELETE");
        btdelete.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 80, 30));

        btdelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        btdelete1.setText("CLOSE");
        btdelete1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 70, 20));

        btnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bNew.png"))); // NOI18N
        btnew.setText("NEW");
        btnew.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });
        getContentPane().add(btnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 30));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 400, 120));
        getContentPane().add(txttgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 100, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setText("NO. RESI :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 150, 60, -1));
        getContentPane().add(txtnoresi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, -1));

        btcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SEARCH.PNG"))); // NOI18N
        btcari.setText("CARI");
        btcari.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        getContentPane().add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String getNoresi(){
    String noresi=txtnoresi.getText();
    return noresi;
}
public String getJumlah(){
    String jumlah=txtjumlah.getText();
    return jumlah;
}
public String getTotal(){
    String total=txttotal.getText();
    return total;
}
public String getTgl(){
    String tgl = null;
    if(txttgl.getDate()!=null){
        SimpleDateFormat ganti=new SimpleDateFormat("yyyy-MM-dd");
        tgl=ganti.format(txttgl.getDate());
    }
    return tgl;
}
private Object [][] getData(){
    Object [][] data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st= (Statement) conn.createStatement();
        String query="SELECT * FROM tran_keluar;";
        rs=st.executeQuery(query);
        rs.last();
        int row=rs.getRow();
        rs.beforeFirst();        
        data=new Object[row][4];
        int index=-1;
        while(rs.next()){
            index++;
            data[index][0]=rs.getString("no_resi");
            data[index][1]=rs.getString("jumlah");
            data[index][2]=rs.getString("total");
            data[index][3]=rs.getString("tgl_transaksi");
        }
        st.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, "ERROR karena "+e);
    }
    return data;
}
public void showTable(){
    String [] col_names={"no_resi","jumlah","total","tgl_transaksi"};
    tblTran_keluar=new JTable(getData(), col_names);
    jScrollPane1.setViewportView(tblTran_keluar);
}
    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        String noresi=getNoresi();
        String jumlah=getJumlah();
        String total=getTotal();
        String tgl=getTgl();
        konek.konek();
        String query="INSERT INTO tran_keluar VALUE ('"+noresi+"','"+jumlah+"','"+total+"','"+tgl+"');";
        int x=konek.insert(query);
        if(x==1){
            JOptionPane.showMessageDialog(null,"insert berhasil","INFORMASI",JOptionPane.INFORMATION_MESSAGE);
            showTable();
        } else{
            JOptionPane.showMessageDialog(null,"insert gagal","INFORMASI",JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_btsaveActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        int konfirmasi=JOptionPane.showConfirmDialog(rootPane, "apakah anda yakin ingin menghapus ? ", "haspus",JOptionPane.YES_NO_CANCEL_OPTION);
        if(konfirmasi==JOptionPane.YES_OPTION){
            String no_resi=tblTran_keluar.getValueAt(tblTran_keluar.getSelectedRow(),0).toString();
            try{
                konek.konek();
                PreparedStatement ps=null;
                String query="DELETE FROM tran_keluar WHERE no_resi=?";
                ps=(PreparedStatement) conn.prepareStatement(query);
                ps.setString(1, no_resi);
                int ok=ps.executeUpdate();
                if(ok==1)
                    JOptionPane.showMessageDialog(this,"DELETE berhasil","DELETE",JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this,"DELETE GAGAL","DELETE",JOptionPane.INFORMATION_MESSAGE);
                ps.close();
                showTable();
            } catch(SQLException e){
                System.out.println("HAPUS data GAGAL karena"+e.toString());
            }
        } else{
            System.out.print("penghapusan digagalkan");
        }
}//GEN-LAST:event_btdeleteActionPerformed

    private void btdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelete1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btdelete1ActionPerformed

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        // TODO add your handling code here:
        txtnoresi.requestFocus();
        txtjumlah.setText("");
        txtnoresi.setText("");
        txttgl.setCalendar(null);
        txttotal.setText("");
}//GEN-LAST:event_btnewActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btcariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcari;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btdelete1;
    private javax.swing.JButton btnew;
    private javax.swing.JButton btsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnoresi;
    private javax.swing.JTextField txtnoresi1;
    private com.toedter.calendar.JDateChooser txttgl;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

}
