/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntryEmployee.java
 *
 * Created on Apr 22, 2016, 4:11:06 PM
 */

package Entry;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sipegadaian.koneksi;

/**
 *
 * @author Danny1
 */
public class EntryAdmin extends javax.swing.JInternalFrame {
    /** Creates new form EntryEmployee */
    public EntryAdmin() {
        initComponents();
        showTable();
    }
public koneksi konek=new koneksi();
public Connection conn=null;
public ResultSet rs=null;
public Statement st=null;
public JTable tbAdmin;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btclose = new javax.swing.JButton();
        btnew = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btsave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtidADMIN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();

        setTitle("Entry Employee");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 400, 150));

        btclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1303725710_button_cancel.png"))); // NOI18N
        btclose.setText("CLOSE");
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 120, 30));

        btnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bNew.png"))); // NOI18N
        btnew.setText("NEW");
        btnew.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });
        btnew.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnewFocusGained(evt);
            }
        });
        getContentPane().add(btnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 30));

        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.jpg"))); // NOI18N
        btdelete.setText("DELETE");
        btdelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 30));

        btsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1303725510_disk.png"))); // NOI18N
        btsave.setText("SAVE");
        btsave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, 30));

        jLabel1.setText("ID ADMIN :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 20));
        getContentPane().add(txtidADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 20));

        jLabel3.setText("PASSWORD :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 20));

        txtpass.setText("jPasswordField1");
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formInternalFrameActivated
public String getID(){
    String id=txtidADMIN.getText();
    return id;
}

public String getPass(){
    String pwd=new String(txtpass.getPassword());
    return pwd;
}
    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        String id=getID();        
        String pwd=getPass();
        String query="INSERT INTO login VALUES ('"+id+"','"+pwd+"')";
        konek.konek();
        int ok=konek.insert(query);
        if(ok==1)
            JOptionPane.showMessageDialog(rootPane, "insert okay");
        else
            JOptionPane.showMessageDialog(rootPane, "insert gagal");
        showTable();        
}//GEN-LAST:event_btsaveActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        String idemployee=tbAdmin.getValueAt(tbAdmin.getSelectedRow(),0).toString();
        JOptionPane.showMessageDialog(rootPane, "idemployee ="+idemployee);
        int konf=JOptionPane.showConfirmDialog(this,"Apakah anda yakin ingin dihapus ?","delete",JOptionPane.YES_NO_CANCEL_OPTION);

        if(konf==JOptionPane.YES_OPTION){
            try{
                konek.konek();
                PreparedStatement ps=null;
                String query="DELETE FROM login WHERE nia=?";
                ps=(PreparedStatement) conn.prepareStatement(query);
                ps.setString(1, idemployee);
                int ok=ps.executeUpdate();
                if(ok==1)
                    JOptionPane.showMessageDialog(this,"DELETE berhasil","DELETE",JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this,"DELETE GAGAL","DELETE",JOptionPane.INFORMATION_MESSAGE);
                ps.close();
                showTable();
            } catch (Exception e){

            }
        } else{
            JOptionPane.showMessageDialog(this,"DELETE CANCELED","DELETE",JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_btdeleteActionPerformed

    private void btnewFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnewFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_btnewFocusGained

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        // TODO add your handling code here:        
        txtidADMIN.setText("");        
        txtidADMIN.requestFocus();
        txtpass.setText("");
    }//GEN-LAST:event_btnewActionPerformed

    private void btcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btcloseActionPerformed
public int len(String field){
    int len=field.length();
    return len;
}public Object [][] getData(){
    Object [][]data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st=(Statement) conn.createStatement();
        String query="SELECT * FROM login;";
        rs=st.executeQuery(query);
        rs.last();
        int baris=rs.getRow();
        rs.beforeFirst();
        data=new Object[baris][2];
        int no=-1;
        while(rs.next()){
            no++;
            data[no][0]=rs.getString("nia");
            data[no][1]=rs.getString("password");
        }
        st.close();
    }
    catch(Exception e){

    }
    return data;
}
public void showTable(){
    String []nama_kolom={"ID Admin","Password"};
    tbAdmin =new JTable(getData(), nama_kolom);
    jScrollPane1.setViewportView(tbAdmin);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btclose;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btnew;
    private javax.swing.JButton btsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtidADMIN;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables

}
