/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntryNasabah.java
 *
 * Created on Apr 22, 2016, 6:26:41 PM
 */

package Entry;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sipegadaian.koneksi;

/**
 *
 * @author Danny1
 */
public class EntryNasabah extends javax.swing.JInternalFrame {
public koneksi konek=new koneksi();
public Connection conn=null;
public Statement st=null;
public ResultSet rs=null;
public JTable tabel;
    /** Creates new form EntryNasabah */
    public EntryNasabah() {
        initComponents();
        showTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtidnasabah = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttelp = new javax.swing.JTextField();
        btnew = new javax.swing.JButton();
        btsave = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID NASABAH :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));
        getContentPane().add(txtidnasabah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 80, 20));

        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        txtalamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtalamatFocusGained(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 180, 20));

        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
        });
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 180, 20));

        jLabel2.setText("NAMA :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        jLabel3.setText("ALAMAT :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        jLabel4.setText("NO TELP :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        txttelp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txttelpFocusGained(evt);
            }
        });
        getContentPane().add(txttelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 160, 20));

        btnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bNew.png"))); // NOI18N
        btnew.setText("NEW");
        btnew.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });
        btnew.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnewFocusGained(evt);
            }
        });
        getContentPane().add(btnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 80, 30));

        btsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SAVE.PNG"))); // NOI18N
        btsave.setText("SAVE");
        btsave.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 70, 30));

        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.jpg"))); // NOI18N
        btdelete.setText("DELETE");
        btdelete.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 100, 30));

        btclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close.png"))); // NOI18N
        btclose.setText("CLOSE");
        btclose.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 80, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 350, 140));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setText("KTP / SIM :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public int len(String field){
    int len=field.length();
    return len;
}
   public String getID(){
        String id=txtidnasabah.getText();
        return id;
    }
    public String getNama(){
        String nama=txtnama.getText();
        return nama;
    }
    public String getAlamat(){
        String alamat=txtalamat.getText();
        return alamat;
    }
    public String getTelp(){
        String telp=txttelp.getText();
        return telp;
    }
    private void txtalamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalamatFocusGained
        // TODO add your handling code here:
        if(len(txtnama.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Tidak boleh kosong");
            txtnama.setText("NAME");
            txtnama.requestFocus();
        }
}//GEN-LAST:event_txtalamatFocusGained

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        // TODO add your handling code here:
        if(len(txtidnasabah.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Tidak boleh kosong");
            txtidnasabah.setText("12345");
            txtidnasabah.requestFocus();
        }
        if(len(txtidnasabah.getText())<5 && len(txtidnasabah.getText())>5){
            JOptionPane.showMessageDialog(rootPane, "harus 5 digit");
            txtidnasabah.setText("12345");
            txtidnasabah.requestFocus();
        }
}//GEN-LAST:event_txtnamaFocusGained

    private void txttelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelpFocusGained
        // TODO add your handling code here:
        if(len(txtalamat.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Tidak boleh kosong");
            txtalamat.setText("ADDRESS");
            txtalamat.requestFocus();
        }
}//GEN-LAST:event_txttelpFocusGained

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        // TODO add your handling code here:
        txtidnasabah.setText("");
        txtalamat.setText("");
        txtnama.setText("");
        txtidnasabah.requestFocus();
}//GEN-LAST:event_btnewActionPerformed

    private void btnewFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnewFocusGained
        // TODO add your handling code here:
        if(len(txtalamat.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Alamat employee harus diisi");
            txtalamat.setText("ADDRESS");
            txtalamat.requestFocus();
        }
}//GEN-LAST:event_btnewFocusGained

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        String id=getID();
        String alamat=getAlamat();
        String nama=getNama();
        String telp=getTelp();
        konek.konek();
        String query="INSERT INTO nasabah VALUES ('"+id+"','"+nama+"','"+alamat+"','"+telp+"')";
        int ok=konek.insert(query);
        if(ok==1)
            JOptionPane.showMessageDialog(rootPane, "insert okay");
        else
            JOptionPane.showMessageDialog(rootPane, "insert gagal");
        showTable();

}//GEN-LAST:event_btsaveActionPerformed

    public Object [][] getData(){
    Object [][] data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st= (Statement) conn.createStatement();
        String Query="Select * from nasabah;";
        rs=st.executeQuery(Query);
        rs.last();
        int baris=rs.getRow();
        rs.beforeFirst();        
        data=new Object[baris][4];
        int no=-1;
        while(rs.next()){
            no++;
            data[no][0]=rs.getString("idnasabah");
            data[no][1]=rs.getString("nama");
            data[no][2]=rs.getString("alamat");
            data[no][3]=rs.getString("no_telp");
        }
        st.close();
    }
    catch(Exception e){
        System.out.print("Error Karena = "+e);
    }
    return data;
}
public void showTable(){
    String [] nama_kol={"IdNasabah","Nama","Alamat","No_Telp"};
    tabel =new JTable(getData(),nama_kol);
    jScrollPane1.setViewportView(tabel);
}
    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        String idnasabah=tabel.getValueAt(tabel.getSelectedRow(),0).toString();
        int konf=JOptionPane.showConfirmDialog(this,"Apakah anda yakin ingin dihapus ?","delete",JOptionPane.YES_NO_CANCEL_OPTION);
        if(konf==JOptionPane.YES_OPTION){
            System.out.print("konf = "+konf);

            try{
                konek.konek();
                PreparedStatement ps=null;
                String query="DELETE FROM nasabah WHERE idnasabah=?";
                ps=(PreparedStatement) conn.prepareStatement(query);
                ps.setString(1, idnasabah);
                int ok=ps.executeUpdate();
                if(ok==1)
                    JOptionPane.showMessageDialog(this,"DELETE berhasil","DELETE",JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this,"DELETE GAGAL","DELETE",JOptionPane.INFORMATION_MESSAGE);
                ps.close();
                showTable();
            } catch (Exception e){

            }
        } else{
            JOptionPane.showMessageDialog(this,"DELETE CANCELED","DELETE",JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_btdeleteActionPerformed

    private void btcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btcloseActionPerformed

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btclose;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btnew;
    private javax.swing.JButton btsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtidnasabah;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelp;
    // End of variables declaration//GEN-END:variables

}
