/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntryEmployee.java
 *
 * Created on Apr 22, 2016, 4:11:06 PM
 */

package Entry;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sipegadaian.koneksi;

/**
 *
 * @author Danny1
 */
public class EntryEmployee extends javax.swing.JInternalFrame {
    /** Creates new form EntryEmployee */
    public EntryEmployee() {
        initComponents();
        showTable();
    }
public koneksi konek=new koneksi();
public Connection conn=null;
public ResultSet rs=null;
public Statement st=null;
public JTable tbEmployee;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btclose = new javax.swing.JButton();
        btnew = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btsave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtidemployee = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Entry Employee");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 360, 230));

        btclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1303725710_button_cancel.png"))); // NOI18N
        btclose.setText("CLOSE");
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 120, 30));

        btnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bNew.png"))); // NOI18N
        btnew.setText("NEW");
        btnew.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });
        btnew.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnewFocusGained(evt);
            }
        });
        getContentPane().add(btnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 30));

        btdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.jpg"))); // NOI18N
        btdelete.setText("DELETE");
        btdelete.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, 30));

        btsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1303725510_disk.png"))); // NOI18N
        btsave.setText("SAVE");
        btsave.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 120, 30));

        jLabel1.setText("IDEMPLOYEE :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, 20));
        getContentPane().add(txtidemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, 20));

        txtalamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtalamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtalamatFocusLost(evt);
            }
        });
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 180, 20));

        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
        });
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 180, 20));

        jLabel3.setText("ALAMAT :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 50, 20));

        jLabel2.setText("NAMA :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 40, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PEGAWAI.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formInternalFrameActivated
public String getID(){
    String id=txtidemployee.getText();
    return id;
}
public String getAlamat(){
    String alamat=txtalamat.getText();
    return alamat;
}
public String getNama(){
    String nama=txtnama.getText();
    return nama;
}
    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        String id=getID();
        String alamat=getAlamat();
        String nama=getNama();
        String query="INSERT INTO employee VALUES ('"+id+"','"+nama+"','"+alamat+"')";
        konek.konek();
        int ok=konek.insert(query);
        if(ok==1)
            JOptionPane.showMessageDialog(rootPane, "insert okay");
        else
            JOptionPane.showMessageDialog(rootPane, "insert gagal");
        showTable();
        this.dispose();
}//GEN-LAST:event_btsaveActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        String idemployee=tbEmployee.getValueAt(tbEmployee.getSelectedRow(),0).toString();
        JOptionPane.showMessageDialog(rootPane, "idemployee ="+idemployee);
        int konf=JOptionPane.showConfirmDialog(this,"Apakah anda yakin ingin dihapus ?","delete",JOptionPane.YES_NO_CANCEL_OPTION);

        if(konf==JOptionPane.YES_OPTION){
            try{
                konek.konek();
                PreparedStatement ps=null;
                String query="DELETE FROM employee WHERE idemployee=?";
                ps=(PreparedStatement) conn.prepareStatement(query);
                ps.setString(1, idemployee);
                int ok=ps.executeUpdate();
                if(ok==1)
                    JOptionPane.showMessageDialog(this,"DELETE berhasil","DELETE",JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(this,"DELETE GAGAL","DELETE",JOptionPane.INFORMATION_MESSAGE);
                ps.close();
                showTable();
            } catch (Exception e){

            }
        } else{
            JOptionPane.showMessageDialog(this,"DELETE CANCELED","DELETE",JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_btdeleteActionPerformed

    private void btnewFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnewFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_btnewFocusGained

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        // TODO add your handling code here:
        txtalamat.setText("");
        txtidemployee.setText("");
        txtnama.setText("");
        txtidemployee.requestFocus();
    }//GEN-LAST:event_btnewActionPerformed

    private void btcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btcloseActionPerformed
public int len(String field){
    int len=field.length();
    return len;
}
    private void txtalamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalamatFocusGained
        // TODO add your handling code here:
        if(len(txtnama.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Nama employee harus diisi");
            txtnama.setText("employee");
            txtnama.requestFocus();
        }
}//GEN-LAST:event_txtalamatFocusGained

    private void txtalamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtalamatFocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_txtalamatFocusLost

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        // TODO add your handling code here:
        if(len(txtidemployee.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "ID Employee tidak boleh kosong");
            txtidemployee.requestFocus();
            txtidemployee.setText("12345");
        }
        if(len(txtidemployee.getText())<5 || len(txtidemployee.getText())>5){
            JOptionPane.showMessageDialog(rootPane, "ID Employee Kurang lengkap");
            txtidemployee.setText("12345");
            txtidemployee.requestFocus();
        }
}//GEN-LAST:event_txtnamaFocusGained
public Object [][] getData(){
    Object [][]data=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/pegadaian?;","root","");
        st=(Statement) conn.createStatement();
        String query="SELECT * FROM employee;";
        rs=st.executeQuery(query);
        rs.last();
        int baris=rs.getRow();
        rs.beforeFirst();
        data=new Object[baris][3];
        int no=-1;
        while(rs.next()){
            no++;
            data[no][0]=rs.getString("idemployee");
            data[no][1]=rs.getString("nama");
            data[no][2]=rs.getString("alamat");
        }
        st.close();
    }
    catch(Exception e){

    }
    return data;
}
public void showTable(){
    String []nama_kolom={"idemployee","nama","alamat"};
    tbEmployee =new JTable(getData(), nama_kolom);
    jScrollPane1.setViewportView(tbEmployee);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btclose;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btnew;
    private javax.swing.JButton btsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtidemployee;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

}
